// src/infrastructure/repositories/PrismaPersonIdentityRepository.ts

import type { PrismaClient, PersonIdentity as PrismaPersonIdentity } from '@prisma/client';
import type {
  IPersonIdentityRepository,
  PersonIdentityRecord,
} from '@/domain/personIdentity/repositories/IPersonIdentityRepository';
import type { IdentityProvider } from '@/domain/auth/services/ExternalProviderProfile';

export class PrismaPersonIdentityRepository implements IPersonIdentityRepository {
  constructor(private readonly prisma: PrismaClient) {}

  private map(row: PrismaPersonIdentity): PersonIdentityRecord {
    return {
      id: row.id,
      personId: row.personId,
      provider: row.provider as IdentityProvider,
      providerUserId: row.providerUserId,
      email: row.email ?? null,
      createdAt: row.createdAt,
    };
  }

  async findByProviderAndUserId(
    provider: IdentityProvider,
    providerUserId: string,
  ): Promise<PersonIdentityRecord | null> {
    const row = await this.prisma.personIdentity.findUnique({
      where: {
        // generated by @@unique([provider, providerUserId])
        provider_providerUserId: {
          provider,
          providerUserId,
        },
      },
    });

    return row ? this.map(row) : null;
  }

  async createIdentity(input: {
    personId: number;
    provider: IdentityProvider;
    providerUserId: string;
    email: string | null;
  }): Promise<PersonIdentityRecord> {
    const row = await this.prisma.personIdentity.create({
      data: {
        personId: input.personId,
        provider: input.provider,
        providerUserId: input.providerUserId,
        email: input.email,
      },
    });

    return this.map(row);
  }
}
