// scripts/generate-release.js

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');
const packageJsonPath = path.join(projectRoot, 'package.json');
const outputPath = path.join(projectRoot, '.env.release');

const packageJson = JSON.parse(
  fs.readFileSync(packageJsonPath, 'utf8'),
);

const version = String(packageJson.version ?? '').trim();

if (!version) {
  throw new Error(
    'package.json version is required to generate SENTRY_RELEASE',
  );
}

const sha = execFileSync(
  'git',
  ['rev-parse', '--short', 'HEAD'],
  {
    cwd: projectRoot,
    encoding: 'utf8',
  },
).trim();

if (!sha) {
  throw new Error('Unable to determine current Git SHA');
}

const release = `${version}+${sha}`;

fs.writeFileSync(
  outputPath,
  [
    '# Generated by scripts/generate-release.js - do not edit or commit',
    `SENTRY_RELEASE=${release}`,
    '',
  ].join('\n'),
  'utf8',
);

console.log(`[release] generated ${release}`);